// // import FloatingNavbar from "@/components/navbar/navbar";
// // import type { Metadata } from "next";
// // import type { ReactNode } from "react";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";
// // import { navMenus } from "@/data/navMenus";
// // import { Poppins, Source_Sans_3 } from "next/font/google";
// // import LogoBar from "@/components/logobar/logobar";
// // import Footer from "@/components/footer/footer";
// // import ScrollToTop from "@/components/additional/top";
// // import WhatsAppButton from "@/components/additional/whatsappbutton";
// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Payame Insaniyat Jhansi",
// //   description: "Generated by create next app",
// // };

// // const poppins = Poppins({
// //   subsets: ["latin"],
// //   variable: "--font-heading",
// //   weight: ["400", "500", "600", "700"],
// // });

// // const sourceSans = Source_Sans_3({
// //   subsets: ["latin"],
// //   variable: "--font-body",
// //   weight: ["400", "500", "600"],
// // });


// // export default function RootLayout({ children }: { children: ReactNode }) {
// //   return (
// //     <html lang="en">
// //       <body>
// //         <FloatingNavbar className="app_nav" navItems={navMenus} audioSrc="/audio/audio.mp3"/>
// //         <LogoBar></LogoBar>
// //         {children}
// //         <WhatsAppButton/>
// //         <ScrollToTop/>
// //         <Footer></Footer>
// //       </body>
// //     </html>
// //   );
// // }

// import type { Metadata } from "next";
// import type { ReactNode } from "react";
// import { Poppins, Source_Sans_3 } from "next/font/google";
// import "./globals.css";
// import { GoogleAnalytics } from '@next/third-parties/google';

// import FloatingNavbar from "@/components/navbar/navbar";
// import LogoBar from "@/components/logobar/logobar";
// import Footer from "@/components/footer/footer";
// import ScrollToTop from "@/components/additional/top";
// import WhatsAppButton from "@/components/additional/whatsappbutton";
// import { navMenus } from "@/data/navMenus";
// import Support from "@/components/support/supportbutton";

// const poppins = Poppins({
//   subsets: ["latin"],
//   variable: "--font-heading",
//   weight: ["400", "500", "600", "700", "800"], 
//   display: "swap", 
// });

// const sourceSans = Source_Sans_3({
//   subsets: ["latin"],
//   variable: "--font-body",
//   weight: ["400", "500", "600"],
//   display: "swap",
// });

// export const metadata: Metadata = {
//   metadataBase: new URL("https://www.payameinsaniyatjhansi.in/"),
//   title: {
//     default: "Payam E Insaniyat Forum | Govt. Recognized NGO in Jhansi",
//     template: "%s | Payam E Insaniyat Forum Jhansi", 
//   },
//   description:
//     "Payam E Insaniyat Forum is an 80G Verified NGO in Jhansi, Uttar Pradesh. We are dedicated to eradicating hunger through Roti Bank, providing clothing via Kapda Bank, and offering medical and disaster relief.",
//   keywords: [
//     "NGO in Jhansi",
//     "Payam E Insaniyat Forum",
//     "Roti Bank Jhansi",
//     "Kapda Bank Jhansi",
//     "Donate in Jhansi",
//     "Charity in Uttar Pradesh",
//     "80G Verified NGO",
//     "Medical Camps Jhansi",
//     "Antim Yatra Sewa",
//   ],
//   authors: [{ name: "Payam E Insaniyat Forum" }],
//   creator: "Payam E Insaniyat Forum",
  
//   openGraph: {
//     type: "website",
//     locale: "en_IN",
//     url: "https://www.payameinsaniyatjhansi.in/",
//     title: "Payam E Insaniyat Forum | Bringing Hope & Dignity",
//     description:
//       "Join us in bringing hope, dignity, and opportunity to the underprivileged. Support our Roti Bank, medical camps, and social initiatives in Jhansi.",
//     siteName: "Payam E Insaniyat Forum",
//     images: [
//       {
//         url: "/logo.png", 
//         width: 1200,
//         height: 630,
//         alt: "Payam E Insaniyat Forum Jhansi",
//       },
//     ],
//   },
  
//   twitter: {
//     card: "summary_large_image",
//     title: "Payam E Insaniyat Forum | Govt. Recognized NGO",
//     description:
//       "Join us in bringing hope, dignity, and opportunity to the underprivileged in Jhansi. 100% transparent and 80G Certified.",
//     images: ["/logo.png"],
//   },
  
//   robots: {
//     index: true,
//     follow: true,
//     googleBot: {
//       index: true,
//       follow: true,
//       "max-video-preview": -1,
//       "max-image-preview": "large",
//       "max-snippet": -1,
//     },
//   },
  
//   alternates: {
//     canonical: "/",
//   },
// };

// export default function RootLayout({ children }: { children: ReactNode }) {
//   return (
//     <html lang="en" className={`${poppins.variable} ${sourceSans.variable}`}>
//       <body className="font-body antialiased bg-[var(--theme)] text-[var(--foreground)] overflow-x-hidden flex flex-col min-h-screen">
//         <FloatingNavbar className="app_nav" navItems={navMenus} audioSrc="/audio/audio.mp3" />
//         <LogoBar />
//         <Support/>
//         <main className="flex-grow">
//           {children}
//         </main>
        
//         <WhatsAppButton />
//         <ScrollToTop />
//         <Footer />
//         <GoogleAnalytics gaId="G-4GWYFTV6LV" />
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Fraunces, Instrument_Sans, Instrument_Serif } from "next/font/google";
import "./globals.css";
import { GoogleAnalytics } from '@next/third-parties/google';

import FloatingNavbar from "@/components/navbar/navbar";
import LogoBar from "@/components/logobar/logobar";
import Footer from "@/components/footer/footer";
import ScrollToTop from "@/components/additional/top";
import WhatsAppButton from "@/components/additional/whatsappbutton";
import SplashScreen from "@/components/splash/SplashScreen";
import { navMenus } from "@/data/navMenus";

/**
 * Runs before first paint: if this session has already seen the splash, mark
 * <html> so CSS hides the overlay immediately instead of flashing it again on
 * every navigation.
 */
const SPLASH_GUARD = `try{if(sessionStorage.getItem('pi_splash_seen')==='1'){document.documentElement.classList.add('splash-done')}}catch(e){}`;

/**
 * Display / headings — Fraunces. A variable display serif with `SOFT` and
 * `WONK` axes; dialled in below, it stays warm and human rather than stiff or
 * bookish, which suits an NGO far better than another geometric sans.
 *
 * `axes` must list every non-weight axis we intend to use, otherwise next/font
 * strips them from the subset it generates.
 */
const heading = Fraunces({
  subsets: ["latin"],
  variable: "--font-heading",
  display: "swap",
  axes: ["SOFT", "WONK", "opsz"],
  fallback: ["Georgia", "Times New Roman", "serif"],
});

/**
 * Body — Instrument Sans. A modern grotesque with more personality than the
 * usual neutral workhorses, and it holds up at small sizes in the news feed.
 */
const body = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
  fallback: ["system-ui", "Segoe UI", "sans-serif"],
});

/* Editorial accent — used for pull quotes and emphasis only */
const quote = Instrument_Serif({
  subsets: ["latin"],
  variable: "--font-quote",
  weight: ["400"],
  style: ["normal", "italic"],
  display: "swap",
  fallback: ["Georgia", "serif"],
});


export const metadata: Metadata = {
  metadataBase: new URL("https://www.payameinsaniyatjhansi.in/"),
  title: {
    default: "Payam E Insaniyat Forum | Govt. Recognized NGO in Jhansi",
    template: "%s | Payam E Insaniyat Forum Jhansi", 
  },
  description:
    "Payam E Insaniyat Forum is an 80G Verified NGO in Jhansi, Uttar Pradesh. We are dedicated to eradicating hunger through Roti Bank, providing clothing via Kapda Bank, and offering medical and disaster relief.",
  keywords: [
    "NGO in Jhansi",
    "Payam E Insaniyat Forum",
    "Roti Bank Jhansi",
    "Kapda Bank Jhansi",
    "Donate in Jhansi",
    "Charity in Uttar Pradesh",
    "80G Verified NGO",
    "Medical Camps Jhansi",
    "Antim Yatra Sewa",
  ],
  authors: [{ name: "Payam E Insaniyat Forum" }],
  creator: "Payam E Insaniyat Forum",
  
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: "https://www.payameinsaniyatjhansi.in/",
    title: "Payam E Insaniyat Forum | Bringing Hope & Dignity",
    description:
      "Join us in bringing hope, dignity, and opportunity to the underprivileged. Support our Roti Bank, medical camps, and social initiatives in Jhansi.",
    siteName: "Payam E Insaniyat Forum",
    images: [
      {
        url: "/logo.png", 
        width: 1200,
        height: 630,
        alt: "Payam E Insaniyat Forum Jhansi",
      },
    ],
  },
  
  twitter: {
    card: "summary_large_image",
    title: "Payam E Insaniyat Forum | Govt. Recognized NGO",
    description:
      "Join us in bringing hope, dignity, and opportunity to the underprivileged in Jhansi. 100% transparent and 80G Certified.",
    images: ["/logo.png"],
  },
  
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  
  alternates: {
    canonical: "/",
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="en"
      className={`${heading.variable} ${body.variable} ${quote.variable}`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: SPLASH_GUARD }} />
      </head>
      <body className="font-body antialiased bg-[var(--theme)] text-[var(--foreground)] overflow-x-hidden flex flex-col min-h-screen">
        <SplashScreen />
        <FloatingNavbar className="app_nav" navItems={navMenus} audioSrc="/audio/audio.mp3" />
        <LogoBar />

        <main className="flex-grow">
          {children}
        </main>
        
        <WhatsAppButton />
        <ScrollToTop />
        <Footer />
        <GoogleAnalytics gaId="G-4GWYFTV6LV" />
      </body>
    </html>
  );
}