import FloatingNavbar from "@/components/navbar/navbar";
import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { navMenus } from "@/data/navMenus";
import { Poppins, Source_Sans_3 } from "next/font/google";
import LogoBar from "@/components/logobar/logobar";
import Footer from "@/components/footer/footer";
import ScrollToTop from "@/components/additional/top";
import WhatsAppButton from "@/components/additional/whatsappbutton";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Payame Insaniyat Jhansi",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-heading",
  weight: ["400", "500", "600", "700"],
});

const sourceSans = Source_Sans_3({
  subsets: ["latin"],
  variable: "--font-body",
  weight: ["400", "500", "600"],
});


export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <FloatingNavbar className="app_nav" navItems={navMenus} audioSrc="/audio/audio.mp3"/>
        <LogoBar></LogoBar>
        {children}
        <WhatsAppButton/>
        <ScrollToTop/>
        <Footer></Footer>
      </body>
    </html>
  );
}